/*
 * These are the variables that determine what our central data store (`../reducers/index.js`)
 * changes in our state.
 */

export const CHANGE_FORM = 'CHANGE_FORM'
export const SET_AUTH = 'SET_AUTH'
export const SENDING_REQUEST = 'SENDING_REQUEST'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGOUT = 'LOGOUT'
export const REQUEST_ERROR = 'REQUEST_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const CHANNEL_LIST = 'CHANNEL_LIST'
export const CHANNEL_RECV = 'CHANNEL_RECIEVED'
export const METACONTENT_ALL = 'GET_ALL_METACONTENTS'
export const METACONTENT_RECV = 'GOT_ALL_METACONTENTS'
export const KEYWORD_ALL = 'GET_ALL_KEYWORDS'
export const KEYWORD_RECV = 'GOT_ALL_KEYWORDS'
export const SUBMIT_METACONTENT = "SUBMIT_METACONTENT"
export const SUBMIT_METACONTENT_OK = "SUBMIT_METACONTENT_OK"
export const CREATE_METACONTENT = "CREATE_METACONTENT"
export const CREATE_METACONTENT_READY = "CREATE_METACONTENT_READY"
export const DELETE_METACONTENT = "DELETE_METACONTENT"
export const DELETE_METACONTENT_OK = "DELETE_METACONTENT"
export const DELETE_CHANNEL = "DELETE_CHANNEL"
export const DELETE_CHANNEL_OK = "DELETE_CHANNEL_OK"
export const EDIT_CHANNEL = "EDIT_CHANNEL"
export const EDIT_CHANNEL_OK = "EDIT_CHANNEL_OK"
export const SUBMIT_KEYWORD = "SUBMIT_KEYWORD"
export const SUBMIT_KEYWORD_OK = "SUBMIT_KEYWORD"
